#!/bin/bash

BACKUP_DIR=${BACKUP_DIR:-/data.backup}

mkdir -p $BACKUP_DIR

echo -e "Disaster flag set.\n\nTriggering disaster recovery...this will automatically restart the container."

sleep 3

kill $(pidof etcd)
